spring:
    # DB
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/basic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            connectionTimeout: 5000
            validationTimeout: 1000
            maximumPoolSize: 10
    redis:
        password: root
        port: 6379
        host: localhost

        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
# Token Info
jwt:
    # 무작위 생성된 UUID
    secret:
        Key: 9207dec0-6f8b-11ed-acb2-8f9e0a2f64f1
    # 1 Hour
    access:
        expire: 10800000
    # 1 Day
    refresh:
        expire: 86400000
# AWS 
# AWS 사용을 위해 필수 입력
aws:
    bucket:
        name: bucket
        access:
            key: access_key
        secret:
            key: secret_key

